# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/mavlink/TasarımDosyalari/MGS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1968, 940)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 811, 901))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.firmware = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.firmware.setFont(font)
        self.firmware.setObjectName("firmware")
        self.verticalLayout.addWidget(self.firmware)
        self.ftpdestegi = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ftpdestegi.setFont(font)
        self.ftpdestegi.setObjectName("ftpdestegi")
        self.verticalLayout.addWidget(self.ftpdestegi)
        self.globalloc = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.globalloc.setFont(font)
        self.globalloc.setObjectName("globalloc")
        self.verticalLayout.addWidget(self.globalloc)
        self.globalloc_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.globalloc_2.setFont(font)
        self.globalloc_2.setObjectName("globalloc_2")
        self.verticalLayout.addWidget(self.globalloc_2)
        self.Attitude = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Attitude.setFont(font)
        self.Attitude.setObjectName("Attitude")
        self.verticalLayout.addWidget(self.Attitude)
        self.Velocity = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Velocity.setFont(font)
        self.Velocity.setObjectName("Velocity")
        self.verticalLayout.addWidget(self.Velocity)
        self.GPS = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GPS.setFont(font)
        self.GPS.setObjectName("GPS")
        self.verticalLayout.addWidget(self.GPS)
        self.Groundspeed = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Groundspeed.setFont(font)
        self.Groundspeed.setObjectName("Groundspeed")
        self.verticalLayout.addWidget(self.Groundspeed)
        self.Airspeed = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Airspeed.setFont(font)
        self.Airspeed.setObjectName("Airspeed")
        self.verticalLayout.addWidget(self.Airspeed)
        self.Gimbal = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Gimbal.setFont(font)
        self.Gimbal.setObjectName("Gimbal")
        self.verticalLayout.addWidget(self.Gimbal)
        self.Battery = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Battery.setFont(font)
        self.Battery.setObjectName("Battery")
        self.verticalLayout.addWidget(self.Battery)
        self.EKF = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EKF.setFont(font)
        self.EKF.setObjectName("EKF")
        self.verticalLayout.addWidget(self.EKF)
        self.Heartbeat = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Heartbeat.setFont(font)
        self.Heartbeat.setObjectName("Heartbeat")
        self.verticalLayout.addWidget(self.Heartbeat)
        self.Rangefinder = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rangefinder.setFont(font)
        self.Rangefinder.setObjectName("Rangefinder")
        self.verticalLayout.addWidget(self.Rangefinder)
        self.Rangefinder_Distance = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rangefinder_Distance.setFont(font)
        self.Rangefinder_Distance.setObjectName("Rangefinder_Distance")
        self.verticalLayout.addWidget(self.Rangefinder_Distance)
        self.Rangefinder_voltage = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rangefinder_voltage.setFont(font)
        self.Rangefinder_voltage.setObjectName("Rangefinder_voltage")
        self.verticalLayout.addWidget(self.Rangefinder_voltage)
        self.Heading = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Heading.setFont(font)
        self.Heading.setObjectName("Heading")
        self.verticalLayout.addWidget(self.Heading)
        self.Armable = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Armable.setFont(font)
        self.Armable.setObjectName("Armable")
        self.verticalLayout.addWidget(self.Armable)
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.Mode = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Mode.setFont(font)
        self.Mode.setObjectName("Mode")
        self.verticalLayout.addWidget(self.Mode)
        self.Armed = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Armed.setFont(font)
        self.Armed.setObjectName("Armed")
        self.verticalLayout.addWidget(self.Armed)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionT_rk_e = QtWidgets.QAction(MainWindow)
        self.actionT_rk_e.setObjectName("actionT_rk_e")
        self.action_ngilizce = QtWidgets.QAction(MainWindow)
        self.action_ngilizce.setObjectName("action_ngilizce")
        self.actionAlmanca = QtWidgets.QAction(MainWindow)
        self.actionAlmanca.setObjectName("actionAlmanca")
        self.webEngineView =QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(840, 20, 1101, 901))
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.firmware.setText(_translate("MainWindow", "Autopilot Firmware version:"))
        self.ftpdestegi.setText(_translate("MainWindow", "Autopilot capabilities (supports ftp):"))
        self.globalloc.setText(_translate("MainWindow", "Global Location:"))
        self.globalloc_2.setText(_translate("MainWindow", "Global Location (relative altitude):"))
        self.Attitude.setText(_translate("MainWindow", "Attitude:"))
        self.Velocity.setText(_translate("MainWindow", "Velocity:"))
        self.GPS.setText(_translate("MainWindow", "GPS:"))
        self.Groundspeed.setText(_translate("MainWindow", "Groundspeed:"))
        self.Airspeed.setText(_translate("MainWindow", "Airspeed:"))
        self.Gimbal.setText(_translate("MainWindow", "Gimbal status:"))
        self.Battery.setText(_translate("MainWindow", "Battery:"))
        self.EKF.setText(_translate("MainWindow", "EKF OK?:"))
        self.Heartbeat.setText(_translate("MainWindow", "Last Heartbeat:"))
        self.Rangefinder.setText(_translate("MainWindow", "Rangefinder:"))
        self.Rangefinder_Distance.setText(_translate("MainWindow", "Rangefinder distance:"))
        self.Rangefinder_voltage.setText(_translate("MainWindow", "Rangefinder voltage:"))
        self.Heading.setText(_translate("MainWindow", "Heading:"))
        self.Armable.setText(_translate("MainWindow", "Is Armable?:"))
        self.status.setText(_translate("MainWindow", "System status:"))
        self.Mode.setText(_translate("MainWindow", "Mode:"))
        self.Armed.setText(_translate("MainWindow", "Armed:"))
        self.actionT_rk_e.setText(_translate("MainWindow", "Türkçe"))
        self.action_ngilizce.setText(_translate("MainWindow", "İngilizce"))
        self.actionAlmanca.setText(_translate("MainWindow", "Almanca"))

